/**
 * Mock links for development — matches the CanvaLink model shape
 */
export const mockLinks = [
    {
        id: 'mock-1',
        url: 'https://canva.com/brand/join?token=abc123&referrer=team-invite',
        source: 'scraper',
        sourceRef: 'https://x.com/designer123/status/1',
        authorName: 'Creative Designer',
        status: 'working',
        createdAt: new Date().toISOString(),
        fetchedAt: new Date().toISOString(),
    },
    {
        id: 'mock-2',
        url: 'https://canva.com/brand/join?token=def456&referrer=team-invite',
        source: 'community',
        sourceRef: 'user:community-user-1',
        authorName: 'Art Enthusiast',
        status: 'unverified',
        createdAt: new Date(Date.now() - 3600000).toISOString(),
        fetchedAt: new Date(Date.now() - 3600000).toISOString(),
    },
    {
        id: 'mock-3',
        url: 'https://canva.com/brand/join?token=ghi789&referrer=team-invite',
        source: 'scraper',
        sourceRef: 'https://x.com/designpro/status/3',
        authorName: 'Design Professional',
        status: 'working',
        createdAt: new Date(Date.now() - 7200000).toISOString(),
        fetchedAt: new Date(Date.now() - 7200000).toISOString(),
    },
    {
        id: 'mock-4',
        url: 'https://canva.com/brand/join?token=jkl012&referrer=team-invite',
        source: 'x_api',
        sourceRef: 'https://x.com/creativemind/status/4',
        authorName: 'Creative Mind',
        status: 'broken',
        createdAt: new Date(Date.now() - 10800000).toISOString(),
        fetchedAt: new Date(Date.now() - 10800000).toISOString(),
    },
    {
        id: 'mock-5',
        url: 'https://canva.com/brand/join?token=mno345&referrer=team-invite',
        source: 'community',
        sourceRef: 'user:community-user-2',
        authorName: 'ProDesigner',
        status: 'unverified',
        createdAt: new Date(Date.now() - 14400000).toISOString(),
        fetchedAt: new Date(Date.now() - 14400000).toISOString(),
    },
    {
        id: 'mock-6',
        url: 'https://canva.com/brand/join?token=pqr678&referrer=team-invite',
        source: 'scraper',
        sourceRef: 'https://x.com/canvauser99/status/6',
        authorName: 'Canva Fan',
        status: 'working',
        createdAt: new Date(Date.now() - 18000000).toISOString(),
        fetchedAt: new Date(Date.now() - 18000000).toISOString(),
    },
];
